### PR TITLE
Sync changes from mozilla-central gfx/wgpu

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by moz-gfx** [comment]
bors r=auto

**Comment by kvark** [comment]
well done, thanks!
bors r+

**Comment by kvark** [comment]
@staktrace hmm, so one thing that I don't like here is the backed out CL merged.
I'm thinking that maybe instead of that I'd rather manually get the commit merged and add a new tag?

**Comment by staktrace** [comment]
@kvark That's up to you. Once the PR is generated if you don't like it you can pull it locally and fiddle with it as you please. In this case you can drop the initial landing/backout and repush. As long as all the commits are "linear" (no branches/merges) and you keep the topmost one's commit message intact, there should be no need to manually tag it because the topmost commit already has the hg rev in the commit message. You can tag for extra safety if you want to.

Also if you don't like backout commits in this history I suspect you're going to have to do a lot of manual work. There's no 100% reliable way to have the script strip out commits that get backed out and I don't really want to try. My recommendation would be to just leave them in, but it's your call.

**Comment by kvark** [comment]
Superseded by #506

**Pull request closed without merging**
