### PR TITLE
Snatch bind groups associated with destroyed textures and buffers

### PR DESCRIPTION
**Pull request by nical**
**Connections**

Rebased on top of #5131 

**Description**

Addresses the BindGroup part of https://github.com/gfx-rs/wgpu/issues/5079.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`.
- [x] Run `cargo xtask test` to run tests.

### CODE REVIEW

**Review by ErichDonGubler — APPROVED** [review]
LGTM!

**Comment by ErichDonGubler** [comment]
Restarted CI; looks like the jobs from the last run were manually cancelled. 🤔

**Comment by cwfitzgerald** [comment]
They weren't manually canceled, they're timing out.

**Comment by cwfitzgerald** [comment]
Documenting seems to be taking a long time _sometimes_

**Comment by ErichDonGubler** [comment]
@cwfitzgerald:

> Documenting seems to be taking a long time _sometimes_

Are we running into the issue motivating #5006 again, perhaps?

**Comment by cwfitzgerald** [comment]
Yeah this seems to have re-aggravated the problem. I can reproduce it locally (taking about 2.5min on my M1, so 6min on a virtualized machine doesn't sound crazy.

**Comment by cwfitzgerald** [comment]
I'm going to up the timeout to unblock us, but this needs a separate investigation.

**Pull request merged**
