### PR TITLE
Derive Serialize, Deserialize, Clone for IdentityManager

### PR DESCRIPTION
**Pull request by kunalmohan**
This is required for implementation in servo.

### CODE REVIEW

**Comment by kunalmohan** [comment]
We will have to store`Arc<Mutex<Identities>>` in WorkerGlobalScopeInit(https://github.com/servo/servo/blob/21ed97712586fe1d9d7a4937ba59362e04257def/components/script_traits/lib.rs#L843) while creating a new workerglobalscope.

**Comment by kvark** [comment]
Ok, but `Arc<Mutex<T>>` requires neither of `Serialize`, `Deserialize`, or `Clone`.

**Comment by kunalmohan** [comment]
Huh..I wonder why it has been throwing this error then :thinking: 
```
error[E0277]: the trait bound `identityhub::Identities: serde::Deserialize<'_>` is not satisfied
   --> components/script_traits/lib.rs:867:5
    |
867 | /     /// Channel to WebGPU
868 | |     pub gpu_id_hub: Arc<Mutex<Identities>>,
    | |__________________________________________^ the trait `serde::Deserialize<'_>` is not implemented for `identityhub::Identities`
    |
    = note: required because of the requirements on the impl of `serde::Deserialize<'_>` for `std::sync::Mutex<identityhub::Identities>`
    = note: required because of the requirements on the impl of `serde::Deserialize<'_>` for `std::boxed::Box<std::sync::Mutex<identityhub::Identities>>`
    = note: required because of the requirements on the impl of `serde::Deserialize<'_>` for `std::sync::Arc<std::sync::Mutex<identityhub::Identities>>`
    = note: required by `serde::de::SeqAccess::next_element`
```

**Comment by kvark** [comment]
That's because the whole `WorkerGlobalScopeInit` wants to be deserialized. Why do you need the `IdentityManager` in that struct anyway?

**Comment by kunalmohan** [comment]
To share the gpu_id_hub among all the threads in a process I am creating one and storing it in the script_thread as `Arc<Mutex<Identities>>`. So every time a new globalscope object is created, a clone of that hub is passed to it. One of the places where a new globalscope is created is in  [workerglobalscope.rs](https://github.com/servo/servo/blob/21ed97712586fe1d9d7a4937ba59362e04257def/components/script/dom/workerglobalscope.rs#L132) which accepts `WorkerGlobalScopeInit` as an argument.

**Comment by kvark** [comment]
Ok, I'm still missing one thing. If one needs to share something between threads, it doesn't require serialization, it's just `Send`. Perhaps, there is a particular reason for the serialize requirement there?

I'm concerned because deserializing `Arc<something>` is not what you want here, at all. When deserializing, you don't get the `Arc` sharing things, it's basically creating a new object, and a new `Arc`. This is useful for communicating between processes, since you can't have `Arc` sharing of data visible from both processes.

**Comment by kunalmohan** [comment]
So I did some digging, read another blog on Servo infrastructure, read the WebGPU spec again, and realized that this is not required :sweat_smile: . WorkerGlobalscopeInit is required by DedicatedWorkers or ServiceWorkers and GPU objects can only be accessed by window and DedicatedWorkers. The Serialize and Deserialize traits were required because Service Workers exist in separate processes than content processes in Servo. So, I have passed the hub as a separate argument from WorkerGlobalScopeInit while creating a workerglobalscope for either of the workers.

**Comment by kvark** [comment]
Interesting... if a service worker runs in a different process, and yet it wants to access the same GPU resources as the main process, we'd need some complicated machinery to ensure these properly manage object IDs. Perhaps, for the nearest time being, we can focus on the case where one wgpu server is only accessed by a single content process. Later we can come back to workers.

**Pull request closed without merging**
