### PR TITLE
Minor error reporting fixes

### PR DESCRIPTION
**Pull request by kvark**
Addresses https://phabricator.services.mozilla.com/D72065

### CODE REVIEW

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Pull request merged**
