### PR TITLE
Re-enable latest nightly on CI

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by kvark** [comment]
Let's see if this works now.
bors r+

**Comment by kvark** [comment]
bors try

**Comment by kvark** [comment]
Blocked by https://github.com/Xudong-Huang/generator-rs/issues/21

**Comment by kvark** [comment]
bors try

**Comment by kvark** [comment]
why on earth does it keep using generator-0.6.20?..

**Comment by Systemcluster** [comment]
`cargo test` seems to just use the version from `Cargo.lock` which still contains `0.6.20`

**Comment by kvark** [comment]
oh snap, I totally forgot that we have Cargo.lock now

**Pull request closed without merging**
