### PR TITLE
Backport Do not feed &"" to D3DCompile (#5812) to 0.20

### PR DESCRIPTION
**Pull request by torokati44**
This is https://github.com/gfx-rs/wgpu/pull/5812 backported to the `v0.20` branch.

### CODE REVIEW

**Comment by torokati44** [comment]
Ah, I just saw that @Elabajaba is on this _right now_, so feel free to close this with no further explanation. Sorry for the spam!

**Comment by Elabajaba** [comment]
Whoops, didn't notice this when I opened mine.

I'll close mine for 0.20.

**Review by ErichDonGubler — APPROVED** [review]

**Comment by ErichDonGubler** [comment]
Just awaiting release (CC @cwfitzgerald).

**Comment by torokati44** [comment]
Is there an estimate of when/if the next 0.20.x release will be out?
Not trying to rush anything, just so we can better judge whether we should go forward with https://github.com/ruffle-rs/ruffle/pull/16786, or wait for a release.

**Comment by torokati44** [comment]
Oh, sorry, I just noticed https://github.com/gfx-rs/wgpu/pull/5850, never mind then.

**Pull request merged**
