### PR TITLE
Pipeline constants

### LINKED ISSUE #1762: Pipeline overrides
**Is your feature request related to a problem? Please describe.**
See https://github.com/gpuweb/gpuweb/pull/886

**Describe the solution you'd like**
Just follow the spec

**Describe alternatives you've considered**
?

**Additional context**

### LINKED ISSUE #4366: Pipeline-overridable constants
Related to gfx-rs/naga#647
Required by https://github.com/gfx-rs/wgpu/issues/1762

### PR DESCRIPTION
**Pull request by teoxoy**
It's time 🎉 

Resolves https://github.com/gfx-rs/wgpu/issues/4366 & resolves https://github.com/gfx-rs/wgpu/issues/1762.

All commits have been previously approved in the following PRs:
- https://github.com/gfx-rs/wgpu/pull/4730
- https://github.com/gfx-rs/wgpu/pull/4845
- https://github.com/gfx-rs/wgpu/pull/4793
- https://github.com/gfx-rs/wgpu/pull/4998
- https://github.com/gfx-rs/wgpu/pull/5249
- https://github.com/gfx-rs/wgpu/pull/5387
- https://github.com/gfx-rs/wgpu/pull/5419
- https://github.com/gfx-rs/wgpu/pull/5492
- https://github.com/gfx-rs/wgpu/pull/5495

There are still 2 features that remain to be implemented:
- https://github.com/gfx-rs/wgpu/issues/4450
- https://github.com/gfx-rs/wgpu/issues/5315

Commits should not be squashed (they are self-contained and passed CI individually).

### CODE REVIEW

**Review by jimblandy — APPROVED** [review]
All these changes have been previously reviewed as PRs to the `pipeline-constants` branch.

**Comment by AdrianEddy** [comment]
Wooo! Thanks for all your efforts, I've been waiting for this for a long time! Great job!

**Comment by hannesojala** [comment]
This is awesome! Is there a reason that the constants field isn't an `Option<_>`? Haven't thought too deeply about this, just curious.

**Comment by ErichDonGubler** [comment]
@hannesojala: Well, let's start thinking, then! 😉 Why would you want an `Option`? Does it offer something you expected that `HashMap` does not?

AFAIK, `HashMap` affords everything one might want, particularly an implementation of `Default`.

**Comment by hannesojala** [comment]
That makes perfect sense! I was only thinking from a semantic clarity perspective, but that's not everything, of course.

**Pull request merged**
