### PR TITLE
Port to gfx-hal-0.6

### PR DESCRIPTION
**Pull request by kvark**
This got a little more involved than I hoped, because of https://github.com/rust-lang/rust/issues/34433 which is unfortunately closed.

### CODE REVIEW

**Comment by rukai** [comment]
should we move the actual 0.6 version change into a separate PR, to give people a chance to test the changes before we do the release?

**Comment by kvark** [comment]
@rukai great idea! I'll remove the second commit from here, just waiting for https://github.com/gfx-rs/gfx/pull/3341 first
Note: starting with 0.6, gfx-rs becomes truly an implementation detail, and we will be able to switch to breaking versions without affecting the users of wgpu. Somehow, I don't think we'll need this though :)

**Comment by kvark** [comment]
Actually, this doesn't need to be blocked on gfx Android support. It's ready for review now.

**Comment by kvark** [comment]
Tested on wgpu-rs on Metal. Let's proceed
bors r+

**Comment by kvark** [comment]
Lukas, have you had a chance to check your code for compatibility?

**Comment by rukai** [comment]
I'm at work atm, will be able to in ~8 hours

**Comment by rukai** [comment]
wgpu-rs master works great on all my projects!

**Pull request merged**
