### PR TITLE
Use Static-DXC for Tests Locally

### PR DESCRIPTION
**Pull request by cwfitzgerald**
See #6558

### CODE REVIEW

**Comment by teoxoy** [comment]
I think that as long as we support FXC we should test it as well; especially that it's more constrained than DXC.

**Comment by cwfitzgerald** [comment]
That's fine, but it probably needs to be by some other mechanism in the tests. The current state of affairs is that dxc is run in CI (so that raytracing and other advanced features can actually run) so this just makes this match it so local results are consistent with CI.

If we want to either change the default or enable a mechanism for testing with fxc as well, that's fine, but orthogonal.

**Comment by teoxoy** [comment]
Ah, I see - I missed the fact that CI doesn't already test with FXC.

**Review by teoxoy — APPROVED** [review]

**Comment by cwfitzgerald** [comment]
Filed https://github.com/gfx-rs/wgpu/issues/6754

**Pull request merged**
