### PR TITLE
Add support for indirect dispatch

### PR DESCRIPTION
**Pull request by dragly**

### CODE REVIEW

**Comment by dragly** [comment]
@kvark regarding your comment on #247 regarding that it definitely should be `BufferUsage::INDIRECT` and not `BufferUsage::STORAGE`: I am getting the following error when I try to call `use_extend` with `BufferUsage::INDIRECT`:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: STORAGE'
```

Any idea why this might happen and how to proceed? The buffer is created as follows:

```rust
let dispatch_buf = device
    .create_buffer_mapped(
        1,
        wgpu::BufferUsage::INDIRECT | wgpu::BufferUsage::TRANSFER_SRC | wgpu::BufferUsage::STORAGE,
    )
    .fill_from_slice(&dispatch_data);
```

If I create it without the `STORAGE`, Vulkan will complain on validation when I try to write to the buffer from a compute shader.

**Comment by kvark** [comment]
How do I repro your problem? Could you share the call stack?

**Comment by kvark** [comment]
Oh, nevermind. We should just be using `use_replace` here instead of `use_extend`.

**Comment by kvark** [comment]
perfecto!
bors r+

**Pull request merged**
