### PR TITLE
[naga] Use `HandleSet` instead of `BitSet` where appropriate

### PR DESCRIPTION
**Pull request by jimblandy**
Use the more strictly-typed `HandleSet` for sets of arena handles, rather than the untyped `BitSet`.

This depends on #5862, so it's marked as a draft PR for now.

-   [naga] Move `HandleSet` from `compact` into `arena`.

-   [naga] Use `HandleSet` in `naga::proc::index`.

    Change `naga::proc::index::find_checked_indexes` to return a
    `HandleSet<Expression>`, rather than an untyped `BitSet`.

    Fix uses in the Metal Shading Language backend.

-   [naga] Change `HandleSet::insert` to return a `bool`.

    Change `HandleSet::insert` to return `true` if the handle was not
    already in the set.

    Change uses in `naga::compact` which were taking advantage of the
    prior return type of `()` to avoid needing to use semicolons in
    `match` arms.

-   [naga] Use `HandleSet` in `Validator::valid_expression_set`.

    Add `HandleSet` methods `new`, `clear`, `clear_for_arena`, and
    `remove`.

    Change the type of `naga::valid::Validator::valid_expression_set` from
    `BitSet` to `HandleSet`. Adjust uses.

-   [naga spv-out] Use `HandleSet` in `ExpressionConstnessTracker`.

    Change `naga::back::spv::ExpressionConstnessTracker::inner` from a
    `BitSet` to a `HandleSet<Expression>`. Adjust uses.

-   [naga] Use `HandleSet` in `Validator::needs_visit`.

    Change the type of `naga::valid::Validator::needs_visit` from `BitSet`
    to `HandleSet`. Adjust uses.

    Add `HandleSet` method `iter`.

### CODE REVIEW

**Review by ErichDonGubler — APPROVED** [review]
A nice ergonomic win. <sub>I ain't no @gfx-rs/naga member, tho. 😅</sub>

**Comment by ErichDonGubler** [comment]
This was also EZ to review. Kudos!

image

**Comment by jimblandy** [comment]
rebased, now that #5862 has been merged

**Review by teoxoy — APPROVED** [review]
Good stuff!

**Pull request merged**
