### PR TITLE
Permit non-struct, non-array types as buffers.

### LINKED ISSUE #2583: Bad global type in WGSL causes `create_shader_module` to panic, not return an error
If you call `wgpu_core::Global::create_shader_module` with WGSL that has a `var<uniform>` of type `mat2x2<f32>`, and an entry point that uses it, the module passes Naga validation, but `wgpu_core::validation::Interface::new` panics.

To reproduce:

```
use anyhow::Result; // anyhow = "1"
use futures_executor::block_on; // futures-executor = "0.3"

fn main() -> Result<()> {
    let instance = wgpu::Instance::new(wgpu::Backends::VULKAN);

    let (device, queue) = block_on(async {
        let adapter = instance.request_adapter(&wgpu::RequestAdapterOptions::default())
            .await
            .expect("request_adapter returned None");
        adapter.request_device(&wgpu::DeviceDescriptor {
            label: Some("play-wgpu device"),
            features: wgpu::Features::default(),
            limits: wgpu::Limits::default(),
        },
                               None).await
    })?;

    let module = device.create_shader_module(&wgpu::ShaderModuleDescriptor {
        label: Some("play-wgpu shader module"),
        source: wgpu::ShaderSource::Wgsl("
            @group(0) @binding(0) var<uniform> xform: mat2x2<f32>;
            @stage(compute) @workgroup_size(32) fn main() { let use_it = xform; }
        ".into())
    });

    drop((module, queue));

    Ok(())
}
```

Because `xform` has an unexpected type for a global, there is no entry created for it in `Interface::new`'s `resource_mapping` table, and then trying to push the `EntryPoint::resources` entry for `main`'s use of `xform` panics.

### PR DESCRIPTION
**Pull request by jimblandy**
Fixes #2583.

### CODE REVIEW

**Comment by jimblandy** [comment]
Unfortunately, this is wrong, because the cube example breaks.

**Comment by jimblandy** [comment]
This is interesting:

```
[2022-04-07T05:38:28Z ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
    Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7f0f248b4160, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 21 decorated as Block must be explicitly laid out with MatrixStride decorations.
      %_struct_21 = OpTypeStruct %mat4v4float
    
[2022-04-07T05:38:28Z ERROR wgpu_hal::vulkan::instance] objects: (type: DEVICE, hndl: 0x7f0f248b4160, name: ?)
[2022-04-07T05:38:28Z ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
    Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7f0f248b4160, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 21 decorated as Block must be explicitly laid out with MatrixStride decorations.
      %_struct_21 = OpTypeStruct %mat4v4float
```

**Comment by jimblandy** [comment]
Work is proceeding here in naga#1815.

**Comment by jimblandy** [comment]
With gfx-rs/naga#1815 and gfx-rs/naga#1823, this branch works.

**Comment by cwfitzgerald** [comment]
Something went real bad on CI here.

**Comment by jimblandy** [comment]
The CI failures seem to be gfx-rs/naga#1836 and gfx-rs/naga#1837.

**Review by kvark — APPROVED** [review]

**Comment by jimblandy** [comment]
[Permit non-struct, non-array types as buffers. wgpu#2584](https://trello.com/c/axK9b9iv/2-permit-non-struct-non-array-types-as-buffers-wgpu2584)

**Pull request merged**
