### PR TITLE
Update Support Platforms Table to Have a Key

### LINKED ISSUE #531: Clarify Readme Supported Platform Table
It's a little unclear to me what all the symbols mean and how they relate to each other. Obviously the green checkmark means supported, but what does the lighter checkmark mean? Also it took to looking at the markdown source to figure out what the symbol for opengl meant.

It would just be nice to have a little key to explain it :)

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Closes #531 

I have added wording that I believe is accurate, but if there is better wording, feel free to propose it.

### CODE REVIEW

**Comment by kvark** [comment]
Can we have the legend occupying less space? i.e. put it alongside the table on the right, or as a one-liner blow it?

**Comment by cwfitzgerald** [comment]
How does that look?

**Comment by kvark** [comment]
Good, just need some better separation between them. Maybe separate by commas?

**Comment by cwfitzgerald** [comment]
Emdashes should be separated enough without being distracting

**Comment by kvark** [comment]
Cool, thanks! Could you squash the commits together?

**Comment by cwfitzgerald** [comment]
Squashed and rebased

**Pull request merged**
