### PR TITLE
hal/egl: defer surface initialization to configure() time

### LINKED ISSUE #1492: Segmentation Fault on Hello Triangles Example
**Description**
Running the hello triangles example gives:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/wpguvoxels`
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.8.1/src/device/mod.rs:4477:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:457:5
   2: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.8.1/src/device/mod.rs:4477:29
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:794:27
   4: wgpu::Device::create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/lib.rs:1659:17
   5: wpguvoxels::run::{{closure}}
             at ./src/main.rs:75:26
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/future/mod.rs:80:19
   7: pollster::block_on
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
   8: wpguvoxels::main
             at ./src/main.rs:136:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    567099 segmentation fault (core dumped)  RUST_BACKTRACE=1 cargo run
```

**Platform**
I am running this on Arch Linux x64 with BSPWM and an Nvidia 1070 driver version 465.31 (using nvidia-dkms package).

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Fixes #1492

**Description**
I think EGL initializing the surface makes it unavailable for Vulkan later on. So here we are moving this initialization from `create_surface` to `configure` time.

**Testing**
Untested.

### CODE REVIEW

**Comment by PolyMeilex** [comment]
I can confirm that it works as expected now,  OpenGL backend on my machine fails to initialize, and it now correctly falls back to Vulcan backend as it should

**Comment by kvark** [comment]
Bad news is - I tested it on Linux/AMD, and this gets us "code 0x3003: dri3_surface_creation" failure in GL :(

**Comment by kvark** [comment]
A bit more work was required to get the window pointers moved to the configure stage. This is ready now.

**Comment by rukai** [comment]
This fixes the `hello_triangle` example on linux + nvidia gtx 960.
I also checked no regressions on the cube example.

**Comment by pythonesque** [comment]
The create_surface function is still unsafe (due to raw window handle issues).

Also, have you tested what happens when you try to reuse the window afterwards?  Currently we call

`surface.presentation.take()`

during configuration which means we error, but then remove evidence that the surface was already configured...

**Comment by kvark** [comment]
Ok, I think we need to get this in, and follow-up with addressing @pythonesque concerns.

**Pull request merged**
