### PR TITLE
Fix a few entry_point parameters

### PR DESCRIPTION
**Pull request by nical**
**Description**

A few must have been missed in #5148 and somehow CI let it pass but caught it in #6030.

### CODE REVIEW

**Review by teoxoy — APPROVED** [review]

**Review by ErichDonGubler — APPROVED** [review]

**Comment by ErichDonGubler** [comment]
I can see how that happened/that PR became necessary. Those tests were added after the original base of the optional entry point PR. `$OP`-and-merging would not have caught that for either of them unless somebody had rebased and then checked CI after the other had merged. 😅

This is a point in favor of forcing PRs to be up-to-date before bringing into mainline history; CC @jimblandy, @cwfitzgerald.

**Comment by cwfitzgerald** [comment]
Forcing PR's to be up to date is really annoying, but this is a good argument due merge trains, which we can enable.

**Comment by sagudev** [comment]
> $OP-and-merging would not have caught that for either of them unless somebody had rebased and then checked CI after the other had merged. 😅
>
> This is a point in favor of forcing PRs to be up-to-date before bringing into mainline history

We use GitHub's merge queue in servo for this.

**Comment by ErichDonGubler** [comment]
Oddly, MacOS CI [timed out](https://github.com/gfx-rs/wgpu/actions/runs/10076181546/job/27856554274?pr=6031#step:13:521). Re-running.

**Comment by ErichDonGubler** [comment]
Even if CI times out again, this PR is likely worth pushing to mainline anyway, since it fixes compilation failures. 😅

**Comment by teoxoy** [comment]
> Oddly, MacOS CI [timed out](https://github.com/gfx-rs/wgpu/actions/runs/10076181546/job/27856554274?pr=6031#step:13:521). Re-running.

Yeah, it started with https://github.com/gfx-rs/wgpu/pull/6021.

**Pull request merged**
