### PR TITLE
Allow 64-bit hex literals and const-evaluate unary ops

### LINKED ISSUE #6615: `0x8000000000000000` is not accepted as a `u64` literal
**Description**

Naga incorrectly rejects 64-bit literals that wouldn't fit in an `i64`, but do fit in a `u64`.

**Repro steps**

When enabling the `SHADER_INT64` feature, the following shader is incorrectly rejected:

```wgsl
const aa: u64 = 0x7fffffffffffffff;
const bb: u64 = 0x8000000000000000;
```

```
Shader '' parsing error: numeric literal not representable by target type: `0x8000000000000000`
   ┌─ wgsl:33:17
   │
33 │ const bb: u64 = 0x8000000000000000;
   │                 ^^^^^^^^^^^^^^^^^^ numeric literal not representable by target type


      numeric literal not representable by target type: `0x8000000000000000`
```

**Expected vs observed behavior**
This should work.

### PR DESCRIPTION
**Pull request by SludgePhD**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/6615

**Description**
`lu` and `li` suffixes on hex literals now treat them as `u64` and `i64`, respectively, to match the behavior with decimal literals.
Unary operations on 64-bit numbers can now be const-evaluated to allow negative literals.

**Testing**
The existing test was modified to use hex literals in addition to decimal literals.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Review by jimblandy — APPROVED** [review]
LGTM.

**Comment by ErichDonGubler** [comment]
Is this functionality gated behind a feature? I'm concerned this might be exposed by default.

**Comment by SludgePhD** [comment]
@ErichDonGubler the validation pass checks for `u64` and `i64` and fails unless the `INT64` feature is enabled. I think that will catch all literals too?

**Comment by jimblandy** [comment]
> @ErichDonGubler the validation pass checks for `u64` and `i64` and fails unless the `INT64` feature is enabled. I think that will catch all literals too?

@ErichDonGubler That's a great thing to bring up. But it looks to me like we're doing this right.

The right way to gate this is for the WGSL front end to accept everything, and for the validator to decide what's permitted and what is not. If I'm reading correctly, this should be working fine:

- `Validator::validate_const_expression` and `Validator::validate_expression` both handle `Expression::Literal` by calling `Validator::validate_literal`.
- `Validator::validate_literal` calls `Validator::check_width`.
- `Validator::check_width` checks the right `Capabilities` flags for 64-bit floats and integer literals.

In `Validator::validate_type`, we also have calls to `check_width` for `TypeInner::Scalar`, `Vector`, `Matrix`, and `ValuePointer`. `Atomic` does its own width validation, checking different `Capabilities` flags for 64-bit atomics.

**Pull request merged**
