### PR TITLE
Update `ash` to `0.37`

### PR DESCRIPTION
**Pull request by a1phyr**
This raises MSRV to 1.59, not sure if this is acceptable.

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
I'm good with this, but MSRV bump needs a look by @kvark - who are the stakeholders who might have an issue with this?

**Comment by kvark** [comment]
We should give a heads up to Bevy, Dotrix, Rend3, etc.
Not as much worried about Gecko, since it's very close to the latest stable at all times.

**Comment by a1phyr** [comment]
I did a little investigation:
- Bevy uses latest stable
- Rend3 uses 1.57
- I could not find the information for Dotrix and Vange-rs
- Veloren uses nightly but is still using an old `wgpu` version anyway

**Comment by kvark** [comment]
Thank you!
So let's go with it.

**Review by kvark — APPROVED** [review]

**Pull request merged**
