### PR TITLE
[0.2] Scissor test

### PR DESCRIPTION
**Pull request by snuk182**
A backport of scissor test from master to 0.2.

### CODE REVIEW

**Comment by kvark** [comment]
please bump the patch versions and required wgou-native dependency of wgpu-rs

**Comment by snuk182** [comment]
Then the question arises - why `wgpu-native`'s git version is 0.2.5, its crates version is 0.2.6, and what number should I place there?

**Comment by kvark** [comment]
Where are you seeing the git version to be 0.2.5?
Look at https://github.com/gfx-rs/wgpu/blob/v0.2/wgpu-native/Cargo.toml#L3

**Comment by snuk182** [comment]
Bah. I missed the place where I have seen the wrong number. Here it is: https://github.com/gfx-rs/wgpu/blob/v0.2/wgpu-rs/Cargo.toml#L26

**Comment by kvark** [comment]
That's a dependency. It needs to point to a minimal version required (by this crate), not to the latest version published.

**Comment by snuk182** [comment]
Fair.

**Pull request merged**
