### PR TITLE
Upgrade `arrayvec` to 0.7

### PR DESCRIPTION
**Pull request by a1phyr**
Upgrade `arrayvec` to version 0.7 (using const generics).

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
Good to go after CI is happy

**Comment by a1phyr** [comment]
I forgot to `cargo fmt`

**Comment by kvark** [comment]
Let's not rush this, we need to make sure the MSRV is reasonable here for the clients.

**Comment by a1phyr** [comment]
I thought it would be fine because I could not find any MSRV policy and only `stable` is enforced in CI.

**Comment by kvark** [comment]
@a1phyr you are right, we don't have a policy in place. Especially once teams start forking the project to run on consoles, they'd be very hesitant to update Rust.
So for now, we only have common sense to rely on.
Looks like this PR bumps the MSRV to 1.51. Let's add a badge for it as a follow-up.
bors r+

**Pull request merged**
