### PR TITLE
Sync changes from mozilla-central gfx/wgpu

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by moz-gfx** [comment]
bors r=auto

**Comment by kvark** [comment]
@staktrace wow, something went wrong here. Looks like we haven't detected some of the previously merged PRs.

**Comment by staktrace** [comment]
> @staktrace wow, something went wrong here. Looks like we haven't detected some of the previously merged PRs.

The behaviour is as designed. The sync scripts applies whatever new commits land on m-c to whatever the current version of the `moz-gfx/github-sync` branch is, and then generates the PR. So if other PRs are merged they aren't going to be on the `moz-gfx/github-sync` branch and will be ignored. The reason it works this way is that a previous sync PR might not have gotten merged yet (this happens all the time with WR) so generating a new PR based on master would cause incorrect patch application.

**Comment by staktrace** [comment]
Note that if you want future syncs to work again you should delete the `github-sync` branch in `moz-gfx/wgpu` so it restarts from the latest master.

**Comment by kvark** [comment]
The last sync was #509, and it looks like the github-sync script doesn't see it as a sync point.

**Comment by staktrace** [comment]
There's two different things you need to take into account. One is if the script can accurately build a map of m-c <-> git commits. In the case of #509 it should be able to do that just fine. The other is the state of the `github-sync` branch as I explained above. The commits that it created in #508 were pushed to the `github-sync` branch, and are still sitting there as "unmerged" because #508 was never merged (instead you pushed #509). Unless you delete that branch and force it to recreate from master every PR it creates will have those commits.

**Comment by kvark** [comment]
I see. Is there a reason to not *always* start from the ground up? We have the code, we know the last sync point, why do we need to depend on any stale `github-sync` pointers?

**Comment by staktrace** [comment]
The main reason is efficiency, I guess. See for example the current WR sync PR, which has failed to get merged multiple times. The longer it takes to get merged, the more commits need to go into the PR. If we rebuild the PR from scratch every time, the rebuild process gets longer and longer because we're redoing all the previous work. With the current approach the amount of work is more bounded to just the commits in the m-c merge. Also you'll get a lot of dead PRs, which will make things a bit harder to follow but that's a secondary concern.

From a correctness point of view it should be possible to do what you're suggesting, but it wasn't needed for WR so I didn't really consider that approach in much detail before.

**Comment by kvark** [comment]
Hm, I didn't consider the cost of "building a PR" to be significant to any extent. Do you know some numbers, approximately? i.e. WR PR build grew from 1 second to 10 seconds or something like that?

**Comment by staktrace** [comment]
I don't have numbers, no. It would need to be implemented the other way in order to get numbers, and I never did that. It's probably not significant, I'm just explaining why I did it the way I did. What you're suggesting should be fine.

**Comment by kvark** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1623149

**Pull request closed without merging**
