### PR TITLE
Support `PrimitiveID` under a new feature

### PR DESCRIPTION
**Pull request by initial-algebra**
**Connections**
https://github.com/gfx-rs/wgpu/issues/1669
https://github.com/gfx-rs/naga/pull/1097

**Description**
Added a new flag to `Features` exposing the `Geometry` shader capability which is passed to `naga` for basic validation and SPIR-V code generation.

**Testing**
It seems to work on my machine with a personal project of mine.  The validation has not really been put through its paces.  We should try to produce some bad SPIR-V (e.g. using `PrimitiveID` in a vertex shader) and see what happens.

### CODE REVIEW

**Comment by kvark** [comment]
I don't think this should target v0.9 branch, since adding a capability to Naga is a breaking change, anyway. Let's target `master`?

**Comment by initial-algebra** [comment]
For sure.  v0.9 was just the easiest way to get it working on my machine with my project.

**Comment by kvark** [comment]
> @initial-algebra pushed 250 commits

ok, hold on here...

**Comment by initial-algebra** [comment]
That's my bad, I created a new branch from `master` to reimplement the feature and then merged it back into the branch I created from v0.9 so that this PR would be retained.  Changed the base branch!

**Comment by initial-algebra** [comment]
Closing in favour of https://github.com/gfx-rs/wgpu/pull/1676, which doesn't have as many newbie Git mistakes.

**Pull request closed without merging**
