### PR TITLE
Usage tracking fixes for swapchain and command buffers

### LINKED ISSUE #561: InvalidImageLayout when updating texture between render passes
First of all, congratulations on the release! :tada: It's really great to see all the progress here.

I have migrated `wgpu_glyph` to the latest release in https://github.com/hecrj/wgpu_glyph/pull/33. During the process, I have noticed a validation error was being triggered under some circumstances:

```
[2020-04-07T20:28:50Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout (0)] : Submitted command buffer expects VkImage 0x100000000010[wgpu_glyph::Cache] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
    object info: (type: COMMAND_BUFFER, hndl: 94720332266560)
```

More specifically, the error seems to happen when the glyph cache (a texture) is updated ([using a buffer copy](https://github.com/hecrj/wgpu_glyph/blob/wgpu-validation-error/src/pipeline/cache.rs#L28)) between two render passes. I have modified one of the examples in `wgpu_glyph` to reproduce the issue consistently. It is [the `clipping` example](https://github.com/hecrj/wgpu_glyph/blob/201bb4cec9306494e72f414e8b77a72834d875d4/examples/clipping.rs) in the [`wgpu-validation-error` branch](https://github.com/hecrj/wgpu_glyph/tree/wgpu-validation-error).

It may be relevant to point out that the error does not happen if the texture is _also_ updated before the first render pass. [I needed to add a `frame_count` condition](https://github.com/hecrj/wgpu_glyph/blob/201bb4cec9306494e72f414e8b77a72834d875d4/examples/clipping.rs#L142) and separate the cache updates in different frames to reproduce it.

If the example is too convoluted, I can try to make an SSCCE.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #561 
see description in commit messages

### CODE REVIEW

**Comment by kvark** [comment]
@hecrj this is a suggested fix, it works for the case I tried based on your https://github.com/gfx-rs/wgpu/issues/561#issuecomment-611167969 . I wonder if you can check it on your full case?

Also, I assume you'd want a patch released? Or are you planning on fixing your work to do everything in a single pass?

**Comment by hecrj** [comment]
> I wonder if you can check it on your full case?

I just did. This fixes the validation warning you mentioned, but the validation error is still there:

```
[2020-04-08T22:01:48Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout (0)] : Submitted command buffer expects VkImage 0x100000000010[wgpu_glyph::Cache] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
    object info: (type: COMMAND_BUFFER, hndl: 94591449356960)
```

> Also, I assume you'd want a patch released? Or are you planning on fixing your work to do everything in a single pass?

I plan to, but a patch release would be great in the meanwhile.

**Comment by kvark** [comment]
@hecrj I confirmed this to work on your test case.
It's also fortified by more tests (still not enough!)
bors r+

**Comment by hecrj** [comment]
@kvark Awesome! Just tested it and the error is indeed gone. Thank you :tada:

**Comment by kvark** [comment]
How... on earth did you test and respond so fast?!

**Comment by hecrj** [comment]
Hah, I got an email notifying me of the pushed changes. I just quickly run `cargo update` and `cargo run`.

**Comment by kvark** [comment]
Changes are not platform-specific, so I don't expect any CI breakage.
Version 0.5.1 is ready for pickup with `cargo update -p wgpu-core`

**Pull request merged**
