### PR TITLE
Anger CI

### PR DESCRIPTION
**Pull request by cwfitzgerald**
DO NOT MERGE

### CODE REVIEW

**Comment by crowlKats** [comment]
@cwfitzgerald hm thats weird that its happening out of nowhere; i'll investigate

**Comment by crowlKats** [comment]
@cwfitzgerald cts runner is now fixed

**Comment by crowlKats** [comment]
running is now fixed, though fairly quickly tests fail. do you want me to look into them?

**Comment by cwfitzgerald** [comment]
That would be great - seems to be some CTS/deno mismatch or something - there's no great rush though.

**Comment by crowlKats** [comment]
yea you are right; the runner is set to use a CTS commit from over a year ago. however updating it causes errors with the `run CTS` bash script

**Comment by cwfitzgerald** [comment]
Going to rebase this on top of #3097 soon-ish

**Comment by crowlKats** [comment]
just as a heads-up: requiredLimits option is currently broken due to a problem in deno, so it potentially might take a while until i continue here

**Comment by cwfitzgerald** [comment]
@crowlKats If I pull the CI parts of this, would this be landable - I realize we really shouldn't be having this just sitting around.

**Comment by crowlKats** [comment]
@cwfitzgerald I think so

**Comment by cwfitzgerald** [comment]
Discussed offline that @crowlKats will bring the non-CI changes into a upcoming deno update branch - going to close, but keep the branch alive.

**Pull request closed without merging**
