### PR TITLE
[naga xtask] Minor simplifications.

### PR DESCRIPTION
**Pull request by jimblandy**
Prefer nested `fn` functions over closures when possible. Using a `fn` makes it evident that no values are being captured.

Simplify HLSL loop over entry points.

@ErichDonGubler These are purely style things - if you don't think the new code is more legible, feel free to reject the PR. I just wrote the changes in the process of understanding the code, and figured I might as well see whether anyone else felt similarly.

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `cargo clippy`.
- [X] Run `cargo xtask test` to run tests.
- (not appropriate) Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Review by ErichDonGubler — APPROVED** [review]
🤷🏻‍♂️👍🏻

**Comment by ErichDonGubler** [comment]
Looks like this review only needs another @gfx-rs/naga reviewer, but @teoxoy is out. Any objection to me force-merging, @jimblandy? This is a teeny change, and I expect negligible risk for `trunk`.

**Comment by Wumpf** [comment]
bump @teoxoy :)

**Comment by teoxoy** [comment]
LGTM but it seems it needs to now be rebased.

**Comment by ErichDonGubler** [comment]
This PR has been completely invalidated by <https://github.com/gfx-rs/wgpu/pull/4902>.

**Pull request closed without merging**
