### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by adamnemecek**
**Connections**
None.

**Description**
Refactoring mostly.

**Testing**
None, semantics remain the same.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by Wumpf** [comment]
I appreciate the willingness to help and improve things, but it seems all changes in this PR are merely style changes.
On a quick look none of them seem to bring any tangible improvements (and none are pointed out in the PR description), many are just opinions which aren't covered by any style guide in the repo or checking tool like `clippy` or `cargo fmt` so they will vary from author to author.
As such this is just noise which then needlessly brings the risk implied by any change (a human has to assess if this _really_ doesn't have any hidden changes that may break things) and very likely causes merge conflicts with other PRs in our unfortunately long & slow pipeline.

Please be more mindful of the reviewer's and other contributor's time in the future.

**Comment by adamnemecek** [comment]
It makes things uniform.

**Comment by ErichDonGubler** [comment]
@adamnemecek: The word "uniform" does not, unfortunately, adequately communicate why uniformity is valuable by itself to maintainers or users of WGPU. In other words, there is still no clear problem and solution statement for these changes, which the [PR template you filled out](https://github.com/gfx-rs/wgpu/blob/7078b0a0614c350a84f606a978ec3f10f2d583ba/.github/pull_request_template.md?plain=1#L5) makes it clear we want you to explain:

> Describe what problem this is solving, and how it's solved.

In general, if you only have a vague answer to this prompt when filing a PR against this repository, then expect the PR to be closed without merging. If you would like help determining what to write—or, at the very least, validating the PR before you go to the effort to file it—feel free to request it in [Matrix](https://matrix.to/#/#wgpu:matrix.org).

**Comment by adamnemecek** [comment]
Uniformity in terms of style. Do you think style guides are good?

**Comment by ErichDonGubler** [comment]
@adamnemecek: If you want to continue this conversation, let's do so in [Matrix](https://matrix.to/#/#wgpu:matrix.org); I don't think a PR is an appropriate place and have a larger discussion about style guides.

**Pull request closed without merging**
