### PR TITLE
Add pervasive Naga support to shader module loading

### LINKED ISSUE #1072: Extract shader interface - internal API
Related to https://github.com/gfx-rs/naga/pull/299, we hit a problem where both gfx and wgpu wanted to hold a `naga::Module`. gfx needs it for translation, while wgpu needs it for validation. I'm thinking if, instead of keeping a copy of the module, we should extract the interface from it that's easier to validate. Something along these lines:
```rust
    enum ResourceType {
        Buffer {
            members: Vec<naga::StructMember>,
        },
        Texture {
            dim: naga::ImageDimension,
            arrayed: bool,
            class: naga::ImageClass,
        },
        Sampler {
            comparison: bool,
        },
    }

    struct Resource {
        group: u32,
        binding: u32,
        ty: ResourceType,
    }

    enum NumericType {
        Scalar {
            kind: naga::ScalarKind,
            width: naga::Bytes,
        },
        Vector {
            size: naga::VectorSize,
            kind: naga::ScalarKind,
            width: naga::Bytes,
        },
        Matrix {
            columns: naga::VectorSize,
            rows: naga::VectorSize,
            width: naga::Bytes,
        },
    }

    enum Varying {
        Local {
            location: u32,
            ty: NumericType,
        },
        BuiltIn(naga::BuiltIn),
    }

    struct SpecializationConstant {
        id: u32,
        ty: NumericType,
    }

    struct EntryPoint {
        inputs: Vec<Varying>,
        outputs: Vec<Varying>,
        resources: Vec<naga::Handle<Resource>>,
        spec_constants: Vec<SpecializationConstant>,
    }

    struct Interface {
        resources: naga::Arena<Resource>,
        entry_points: FastHashMap<(naga::ShaderStage, String), EntryPoint>,
    }
```

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Depends on https://github.com/gfx-rs/naga/pull/299 and https://github.com/gfx-rs/gfx/pull/3503
Closes #1072

**Description**
    The purpose of the PR is to support Naga modules everywhere.
    As a requirement, it updates the gfx-rs version used.
    Most of the logic is dedicated towards building a shader interface,
    where previously we just used naga's IR. Now we have our own mini-IR.

**Testing**
Tested in https://github.com/gfx-rs/wgpu-rs/pull/663 (without the experimental feature).
Enabling the experimental feature doesn't work even on the play test that we have - https://github.com/gfx-rs/naga/issues/300

### CODE REVIEW

**Review by grovesNL — APPROVED** [review]
Excited to start passing Naga modules all the way through the stack! This looks great, thank you!

**Review by cwfitzgerald — APPROVED** [review]
Beautiful!

**Comment by kvark** [comment]
bors try

**Review by cwfitzgerald — APPROVED** [review]
LGTM! Always glad to see naga getting futher along :)

**Comment by kvark** [comment]
Bors r=cwfitzgerald

**Pull request merged**
