### PR TITLE
Update gpu-allocator dependency to 0.27

### PR DESCRIPTION
**Pull request by nical**

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
Are there any interesting changes that are supposed to accompany this update? 👀

**Comment by nical** [comment]
I added an API to provide allocation reports to gpu-allocator, but since we only use gpu-allocator on for d3d12 (see #5925) and most wgpu users are on vulkan and metal, there is no rush to merge this before the wgpu release that's coming soon.

That said it seems to simplify the dependency tree a bit so we might want to take it anyway.

In a followup patch I'll expose the allocation reports and that's changelog-worthy, but other than that I don't think there is much to report.

**Comment by Wumpf** [comment]
having fewer versions of windows is a win, on full rebuilds I spend a lot of time building `windows`

**Review by Wumpf — APPROVED** [review]

**Comment by Wumpf** [comment]
gpu-allocator 0.27 changelog https://github.com/Traverse-Research/gpu-allocator/releases/tag/0.27.0

**Pull request merged**
