### PR TITLE
Document coordinate systems in README

### PR DESCRIPTION
**Pull request by MichaelMMacLeod**
I had to do a bit of digging to find information about coordinate systems in
wgpu (asking on Matrix). This commit adds a table of coordinate systems to help
clarify the issue.

The table comes from the DX12 backend documentation of gfx-rs:
https://github.com/gfx-rs/gfx/tree/master/src/backend/dx12

**Connections**
(none)

**Description**
It was difficult for me to find information about what coordinate systems wgpu uses. This commit addresses this issue by adding documentation about wgpu's coordinate systems to the README.

**Testing**
This is purely a documentation change (I have written no tests).

If you want to see how the table looks on Github, check out my fork at https://github.com/MichaelMMacLeod/wgpu/tree/add-coords-to-readme

### CODE REVIEW

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Thanks for this! Couldyou copy the images into `/etc` and then use relative links to get the images? We want the repo to be able to stand on its own.

**Comment by cwfitzgerald** [comment]
Great, thanks! Could you just squash the commits (or merge system doesn't let us do this)?

**Comment by niklaskorz** [comment]
> Great, thanks! Could you just squash the commits (our merge system doesn't let us do this)?

I'm not super familiar with bors, but out of interest, what prevents you to use [`use_squash_merge = true`](https://bors.tech/rfcs/0349-use-a-squash-merge-in-bors.html)?

**Comment by cwfitzgerald** [comment]
Complete lack of knowledge that it exists :) I'll look into seeing that up!

**Comment by cwfitzgerald** [comment]
Thank you!

bors r+

**Review by cwfitzgerald — APPROVED** [review]

**Pull request merged**
