### PR TITLE
player: Add a trailing ']' to the trace if player fails to load the RON file

### PR DESCRIPTION
**Pull request by Kriyszig**
**Connections**
**Issue:** #861 

**Description**
In case of a panic, the RON trace ends without appending a ']' at
the end. Loading this trace as it is will cause a failure while
loading as this doesn't follow the specifications for a valid
RON file.
In case of an error while loading the RON file, we append the ']'
at the end of file and retry. If the error was indeed a missing ']'
the trace is loaded correctly.
If the load fails second time, this means that the trace needs a
manual review for correctness but appending ']' solves most of the
cases of invalid RON file obtained as a result of panic.

**Approach**

The `from_reader` function for RON can be found here - https://github.com/ron-rs/ron/blob/master/src/de/mod.rs#L48
Internally it works as follows

```rust
let mut bytes = Vec::new();
rdr.read_to_end(&mut bytes)?;
from_bytes(&bytes)
```
It reads the bytes into a vector and calls `from_bytes`

As we need to append thr `]` without modifying the trace to keep implementation pure, we extract the file content into a vector and call `from_bytes` on it - this returns a `Result` and in case we come across an error we retry by appending a `]` at the end of the vector and trying again.

**Testing**
The command `cargo test` was run in the player directory which shows all green on my local setup (GNU/Linux)

Being new contributor to this project I'll highly value any and all feedback you can give.
If you feel something needs to be changed / improved or added please let me know and I'll get on it asap!

Thank you

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
This is great, thank you for the PR!
My main question before merging this would be - did you look into making the trace writer to add the `]` on `wgpu` side? This way, the player would need no workaround logic, and the produced RON would be valid by itself, which is useful for highlighting and stuff.

**Comment by Kriyszig** [comment]
> did you look into making the trace writer to add the ] on wgpu side? 
Ah! I haven't yet.
I believe the process would be to find potential spots the program can panic at and add a trailing ']' to the trace.
I can look into this if you would like and come back with the finding

Thank you for the quick review.

**Comment by kvark** [comment]
I mean, consider that path to be unfeasible if there is more than one place to patch. My hope is that - most of the crashes are panics, and panics still trigger `drop` on our objects, so we should have some space to finish the job, by just carefully handling `drop` of the tracing struct.

**Comment by kvark** [comment]
Closing because of https://github.com/gfx-rs/wgpu/issues/861#issuecomment-773444836

**Pull request closed without merging**
