### PR TITLE
Include the glsl global name in entrypoint arguments.

### LINKED ISSUE #5422: BuiltIns / Entrypoint input variables / FunctionArgs do not have a name in glsl-in
This was originally written as https://github.com/gfx-rs/wgpu/issues/5417 but upon investigation this issue was found.

The glsl frontend does not include the builtin name when synthesizing `FunctionArg`s for each `EntryPoint`. My [rust backend](https://github.com/gfx-rs/wgpu/pull/5175) would like to rename the variable name rather than hardcode a mapping between `BuiltIns` and the desired name.

This PR should be reopened if this issue is valid: https://github.com/gfx-rs/wgpu/pull/5418

### PR DESCRIPTION
**Pull request by LegNeato**
This fixes https://github.com/gfx-rs/wgpu/issues/5422.

<strike>This partially addresses https://github.com/gfx-rs/wgpu/issues/5417.</strike>

### CODE REVIEW

**Comment by teoxoy** [comment]
This won't address https://github.com/gfx-rs/wgpu/issues/5417 in the general case. See https://github.com/gfx-rs/wgpu/issues/5417#issuecomment-2013534457.

**Comment by LegNeato** [comment]
@teoxoy Please see the latest comments in https://github.com/gfx-rs/wgpu/issues/5417#issuecomment-2014003766. I think one can argue this is a bug in the way the glsl FE synthesizes `EntryPoint` `FunctionArgument`s

**Comment by teoxoy** [comment]
The test snapshots have to be regenerated.

**Comment by LegNeato** [comment]
> The test snapshots have to be regenerated.

Done

**Review by teoxoy — APPROVED** [review]

**Pull request merged**
