### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by Gordon-F**
Split jobs by OS type

### CODE REVIEW

**Comment by Gordon-F** [comment]
@kvark We still have a matrix for stable/nightly compiler. 

If I understand correctly you want somethings like this?

1. ubuntu_job
1.1 run stable checks
1.2 run nightly checks
2. macos_job
2.1 ...

**Comment by kvark** [comment]
It's not that I *want* that, more that I thought that's what you suggested earlier as an improvement.

**Comment by Gordon-F** [comment]
@kvark Ok, i think we must fix steps with additional dependencies installation on some platforms (Android NDK, for now). If we add some additional targets (iOS Simulator, more android targets, etc.) its get worse.

Maybe better solution for now:
1. iOS job
1. Android job
1. Windows/Linux/MacOS job with Rust stable/nightly

**Comment by kvark** [comment]
Sure, that sounds ok to me.

**Comment by Gordon-F** [comment]
@kvark done.

**Pull request merged**
