### PR TITLE
[0.10] Fix write_texture for array textures

### PR DESCRIPTION
**Pull request by kvark**
Sibling of #1991 for 0.10

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
Same comments as parent PR

**Comment by mitchmindtree** [comment]
Can confirm this fixes #1990 on my setup :+1:

**Comment by UpsettingBoy** [comment]
I can add another confirmation of this fix (commented yesterday over the matrix server).

**Comment by kvark** [comment]
Published in wgpu-core-0.10.4

**Pull request merged**
