### PR TITLE
hal/gles: support externally initialized contexts

### LINKED ISSUE #2344: Pure GL context
**Is your feature request related to a problem? Please describe.**
Sometimes we want to integrate wgpu into a system that already created the window and GL context, and we want to draw something using wgpu's GLES context in addition to other stuff. In this case, EGL isn't involved.

**Describe the solution you'd like**
Some sort of constructor for GLES adapter, used in conjunction with `create_adapter_from_raw`.
This also means working without any Instance, and without any EGL involved.
Would be great to make it not a compile time feature.

**Describe alternatives you've considered**
Separate cargo feature for "raw" mode.

**Additional context**
required for https://github.com/kvark/vange-rs/issues/172

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Closes #2344
cc @lpenguin @caiiiycuk

**Description**
This PR attempts to make minimal set of changes to be able to use GLES in a context we aren't creating.
Overall, I'm happy with the way it turned out, especially `struct EglContext` part.

**Testing**
Comes with a whole example!

### CODE REVIEW

**Comment by caiiiycuk** [comment]
Should I see something if I run halmark test? I only saw this:
изображение

**Comment by caiiiycuk** [comment]
Have the same error as in #2297 , so problem is not related to winit.

https://user-images.githubusercontent.com/1727152/147933733-13935be2-25f3-4a22-9bbd-c77225ef1ce4.mp4

**Comment by caiiiycuk** [comment]
glutin does not support wasm taget (https://github.com/rust-windowing/glutin/issues/1167),  so for wasm need to  create separate example in future.

**Comment by kvark** [comment]
> Have the same error as in #2297

The examples in wgpu-hal aren't handling window resize, and it's not their goal to do so. This is irrelevant of the PR here.

> glutin does not support wasm taget (rust-windowing/glutin#1167), so for wasm need to create separate example in future.

we could put stuff in the same example, just not using glutin, via a bunch of `#[cfg()]`

**Review by cwfitzgerald — APPROVED** [review]

**Pull request merged**
