### PR TITLE
Android support 

### LINKED ISSUE #624: Fix Android support
Basically, port https://github.com/gfx-rs/wgpu-native/pull/5 back here.
cc @francesca64

### PR DESCRIPTION
**Pull request by kvark**
Fixes #624 
Has a part of https://github.com/gfx-rs/wgpu-native/pull/5 plus the CI bits.
Includes #621

### CODE REVIEW

**Comment by Gordon-F** [comment]
@kvark r+. You should also update bors.toml.

I think It would be nice to split jobs by OS. It helps simplify CI and speed up build time. I send PR to fix this.

**Comment by kvark** [comment]
@Gordon-F love the idea, looking forward to i!

**Comment by kvark** [comment]
This is now rebased to exclude #625 
bors r=Gordon-F

**Pull request merged**
