### PR TITLE
Remove all the IPC

### LINKED ISSUE #22: Handle IPC descriptor serialization
Follow-up from #20:
- How do we need to handle serialization/deserialization for descriptors when using IPC?
- Which parts need to be handled within wgpu-native vs. the caller?
- ~~Should we change the types of descriptors to `const uint8_t *desc` (i.e. binary serialized) for the remote case in wgpu.h?~~ (already done)

### LINKED ISSUE #146: remote: handle IPC on Windows
We need to consider some options to support IPC on Windows. The crate which is currently being used https://github.com/servo/ipc-channel states in the README that Windows is not supported yet.

Relevant PRs/issues:
https://github.com/servo/ipc-channel/pull/166
https://github.com/servo/ipc-channel/pull/108
https://github.com/servo/ipc-channel/issues/118

### PR DESCRIPTION
**Pull request by kvark**
Closes #146 
Closes #22

We have decided to use Gecko IPC for Firefox. `wgpu-remote` will therefore provide all the Rust glue that Gecko needs for client and server:
  - initialization/termination of client/server
  - ID management for the client
  - pass encoding blobs

In Servo, we'd need to enable `serde` feature of `wgpu-native` and potentially roll out a different remoting crate that would establish a protocol based on `ipc-channel`, as we wanted originally.

### CODE REVIEW

**Comment by grovesNL** [comment]
Looks like there is an error on one CI task:
```
/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -isysroot /Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9   -o CMakeFiles/remote.dir/main.c.o   -c /Users/travis/build/gfx-rs/wgpu/examples/remote/main.c

In file included from /Users/travis/build/gfx-rs/wgpu/examples/remote/main.c:1:

/Users/travis/build/gfx-rs/wgpu/examples/remote/./../../ffi/wgpu-remote.h:17:10: fatal error: 'cstdarg' file not found

#include <cstdarg>

         ^~~~~~~~~

1 error generated.

make[3]: *** [CMakeFiles/remote.dir/main.c.o] Error 1

make[2]: *** [CMakeFiles/remote.dir/all] Error 2

make[1]: *** [all] Error 2

make: *** [example-remote] Error 2

The command "if [[ $TRAVIS_RUST_VERSION == "nightly" ]] && [[ $TRAVIS_OS_NAME != "windows" ]]; then make VERBOSE=1; fi" exited with 2.
```

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
Argh, windows CI
bors retry

**Pull request merged**
