### PR TITLE
Implement mipmap views on the OpenGL backend

### PR DESCRIPTION
**Pull request by Zoxc**
This makes the `mipmap` example work on AMD HD 5870 / llvmpipe on Windows.

### CODE REVIEW

**Review by cwfitzgerald — COMMENTED** [review]
The code looks fine, and we can leave this to a follow up, but we need to add a downlevel flag for this, and add validation at the wgpu-core level to make sure that any bound texture is only used with one range of mipmaps, so users get proper errors, not corruption.

**Comment by teoxoy** [comment]
We recently talked about this restriction in the committee (https://docs.google.com/document/d/1ERkTrtClVa3JSIGUUaTT3eYR9T8TtM06XNOqrkAdI94/view) and also decided on:

Validate (at draw call time) that all bound textures (not storage textures) share the same mip range.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Hitting this button for admin purposes

**Comment by Zoxc** [comment]
I'm not very familiar with the wgpu-core level so I'll leave that as follow up work.

**Review by cwfitzgerald — APPROVED** [review]

**Pull request merged**
