### PR TITLE
[CI] Fix Vulkan SDK installation

### PR DESCRIPTION
**Pull request by teoxoy**
Used the commands for the 1.3.268 release found here: https://packages.lunarg.com/

### CODE REVIEW

**Comment by teoxoy** [comment]
Looks like it's still not working.

**Comment by cwfitzgerald** [comment]
This isn't related to the vulkan sdk - this is a problem with the builtin repos in apt. All the jobs that touch apt are failing.

**Comment by cwfitzgerald** [comment]
https://github.com/microsoft/linux-package-repositories/issues/130 - should be fixed

**Comment by cwfitzgerald** [comment]
It's resolved

**Pull request closed without merging**
