### PR TITLE
Bump gfx-hal and gpu-alloc

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Absorbs https://github.com/zakarumych/gpu-alloc/pull/31 and https://github.com/gfx-rs/gfx/pull/3548#issuecomment-749158016

**Description**

This fixes the last of the DX11 issues listed in #1059.

**Testing**

Various examples ran.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
What's happening on CI?

**Comment by cwfitzgerald** [comment]
An assertion failure inside of gfx-alloc; above my pay grade.

**Comment by kvark** [comment]
calling @zakarumych

**Comment by cwfitzgerald** [comment]
bors r=kvark

**Pull request merged**
