### PR TITLE
chore: update deno

### PR DESCRIPTION
**Pull request by crowlKats**
Updated #2170

### CODE REVIEW

**Review by littledivy — APPROVED** [review]
LGTM

**Comment by crowlKats** [comment]
Blocked on an issue where running files using any of the webgpu related APIs will exit

**Comment by crowlKats** [comment]
its fixed now

**Review by ErichDonGubler — APPROVED** [review]
Approving here, qualifying that I only took time to really review dependencies and surface-level checks. I think this is appropriate for how much we actually depend on `cts_runner` right now, (which, AIUI, is not at all yet).

**Pull request merged**
