### PR TITLE
add **/Cargo.lock

### PR DESCRIPTION
**Pull request by mahit56**
**Connections**
_Link to the issues addressed by this PR, or dependent PRs in other repositories_

**Description**
_Describe what problem this is solving, and how it's solved._

**Testing**
_Explain how this change is tested._

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Why is this needed?

**Comment by ErichDonGubler** [comment]
I can't speak for the OP (@mahit56, please respond to @cwfitzgerald's prompt!), but I think of a few reasons this sort of change could be good (with a tiny bit more work):

1. Rust upstream announced a change in official guidance on when to check in `Cargo.lock` with [this Rust blog post](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html#why-the-change), which is now "just do it always, end users have the power to update deps. to newer versions under their own power if they need it".
2. This change will make it possible for `naga-cli` to be installed via `cargo install --locked`. We actually _do_ ship binaries from this repository, now that we've brought Naga in-tree, but we never adjusted to uphold official guidance for shipping binaries once that changed.
3. `Cargo.lock` updates from Dependabot tend to reduce downstream surprises, since it has a history and "sudden" changes in transitive deps. become easier to diagnose.
4. We need a checked-in `Cargo.lock` to do lockfile-only updating from Dependabot anyway.

In order for any of these arguments to be valid, though, we need to also actually generate and check in a resolved `Cargo.lock` file, which OP has not done. Happy to do that, if we get consensus on proceeding with a checked-in lockfile.

CC @gfx-rs/wgpu and @gfx-rs/naga for thoughts.

**Comment by jimblandy** [comment]
Also, there is a comment that says:

> # Include the root lockfile but not the others

I guess Erich's comment explains what this was hinting at, but either way it needs to be updated.

**Comment by ErichDonGubler** [comment]
Ah, actually, I think I've misunderstood the intent of this PR. I'm not sure how the existing `*/Cargo.lock` is distinct from `**/Cargo.lock`, except that it would also include the root.

I'm going to close this PR. If I've misunderstood something, please LMK, @mahit56!

**Pull request closed without merging**
