### PR TITLE
Integrate with RenderDoc on winit-less captures

### LINKED ISSUE #623: Hook up player to RenderDoc
Currently, I can't find a way to capture a workload with RenderDoc that doesn't operate on a swapchain. RenderDoc doesn't know when to stop. We could have a simple integration with its API to tell it where the submissions are, or at least when we are done.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #623

### CODE REVIEW

**Comment by kvark** [comment]
@cwfitzgerald it's annoying that renderdoc drags an outdated glutin dependency by default(!).
Anyhow, this is fairly straightforward.
bors r+

**Comment by cwfitzgerald** [comment]
Yeah I agree. If I ever get around to fixing it up, I should also fix that.

**Comment by kvark** [comment]
Getting RenderDoc complaining about the non-coherent atom size being non-respected... and hanging completely :/

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
Dear bors...

**Comment by ebkalderon** [comment]
> it's annoying that renderdoc drags an outdated glutin dependency by default(!).

Sorry for the inconvenience, @kvark. I'm considering upgrading the dependency and disabling that feature by default in the next release, just in case it drifts away again. Feel free to open an issue on the repo so it can be tracked, and feel free to suggest any further improvements you can think of!

**Comment by ebkalderon** [comment]
@kvark @cwfitzgerald I've upgraded the `glutin` dependency to 0.24 and also disabled the integration by default in [v0.9.0](https://github.com/ebkalderon/renderdoc-rs/releases/tag/v0.9.0), which has just been published to [crates.io](https://crates.io/crates/renderdoc/0.9.0). That feature should not have been enabled by default, in retrospect. Apologies again for the inconvenience.

**Pull request merged**
