### PR TITLE
Proper maintenance of the command pools

### LINKED ISSUE #648: Multi threaded memory leak
I encountered severe memory leaks when I added multi-threading to my project. Wgpu consumes a new 50MB every second. I was also able to reproduce this in the wgpu "cube" example, which I pushed here: https://github.com/cart/wgpu-rs/tree/multi-threaded-leak.

I run the render pass in a crossbeam_util thread and pass the CommandBuffer to the main thread via crossbeam channel.

image

### PR DESCRIPTION
**Pull request by kvark**
Fixes #648
This brings the memory consumption on the multi-threaded cube to constant 50Mb.

### CODE REVIEW

**Comment by cart** [comment]
Looks good to me! Of course I'm not a wgpu expert so I can't really review the global effects of this.  But the changes make sense to me from a "local" perspective.

**Comment by kvark** [comment]
Great, thank you!
bors r=cart

**Comment by cart** [comment]
@kvark I may have spoken a bit too soon. These changes do fix the massive memory leak, but we now have a small ~0.2 MB per second leak in the "multithreaded cube" example.

**Comment by cart** [comment]
This new problem only surfaces in multithreaded scenarios. For example, the normal "hello-triangle" example does not suffer from this problem.

**Comment by kvark** [comment]
It's fine, there is never a single last problem:) We'll tackle one at a time. Filed https://github.com/gfx-rs/wgpu/issues/651 to follow up.

**Pull request merged**
