### PR TITLE
Handle 2024-08 spec. rename of image copy APIs

### LINKED ISSUE #6617: Handle 2024-08 spec. renames in image copy APIs
The WebGPU spec. has recently had a bunch of changes to the naming of several APIs related, with no otherwise substantial changes: [`gpuweb`#4838](https://github.com/gpuweb/gpuweb/pull/4838)

Of particular note is that while this change is backwards compatible for a JS implementation of WebGPU, this is _definitely breaking_ for us. 

**Connections**

- Firefox downstream tracking: [bug 1933328](https://bugzilla.mozilla.org/show_bug.cgi?id=1933328)

### PR DESCRIPTION
**Pull request by ErichDonGubler**
Resolves #6617.

_**Recommended review experience is commit-by-commit. Each individual commit should pass CI!**_

### CODE REVIEW

**Comment by crowlKats** [comment]
Would you be able to update the deno JS file & the structs with those names that deno defines as well? If not, no worries and I can do it

**Review by nical — APPROVED** [review]

**Comment by ErichDonGubler** [comment]
@crowlKats: I've handled the rename in `deno_webgpu` with a new stand-alone commit at the tip of this PR. I haven't tested JS execution, but `deno_webgpu` still compiles for me.

**Comment by ErichDonGubler** [comment]
Just holding off on merging here until @crowlKats confirms that things look okay on the Deno end of this PR.

**Review by crowlKats — APPROVED** [review]
perfect, LGTM, thanks!

**Pull request merged**
