### PR TITLE
Update naga revision

### PR DESCRIPTION
**Pull request by munrocket**
**Connections**
https://github.com/gfx-rs/naga/pull/1096

**Description**
Updating `naga` with new WGSL operator `select(f, t, cons)`.

**Testing**
`cargo test` passed

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
This doesn't actually update naga, just our dependencies.

**Comment by munrocket** [comment]
And how to update it? Actually I am interested in new naga for Firefox Nightly, but it seems that gfx-rs already updated.

**Comment by cwfitzgerald** [comment]
https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/Cargo.toml#L39 and a couple other places contain direct commit links to naga. Firefox Nightly will likely take a lot longer to bubble up to, unfortunately, but this is the right first step.

**Review by kvark — APPROVED** [review]
Thank you!
bors r+

**Comment by munrocket** [comment]
Thanks for quick responce. I am not sure that I choose right revision. Just realized that all revision failed on 'dota2' test currently and some of them like commit `e017cb4` just skipped by CI.

**Pull request merged**
