### PR TITLE
Tweak Water Example to Show Off Water Shader a bit More

### PR DESCRIPTION
**Pull request by zicklag**
**Connections**
None

**Description**
Tweaks the water shader example terain and camera to show off the cool water shader a little bit more. 😄

https://user-images.githubusercontent.com/25393315/126842645-e353c0eb-57fc-4b8e-9e0d-901f08c7e9f7.mp4

**Testing**
Tested on vulkan and GL on linux.

### CODE REVIEW

**Comment by kvark** [comment]
would it be possible to raise the water level a bit higher, so that we see more of the water?

**Comment by zicklag** [comment]
Is this better?

image

**Comment by cwfitzgerald** [comment]
This needs to update the test reference image. Could you delete `wgpu/examples/water/screenshot.png` then run `cargo test --example water` to generate a new one.

**Comment by cwfitzgerald** [comment]
Shippit

bors r+

**Pull request merged**
