### PR TITLE
feat: add link feature

### PR DESCRIPTION
**Pull request by crowlKats**
This first requires a release of metal-rs

### CODE REVIEW

**Comment by Wumpf** [comment]
What does this do?

**Comment by crowlKats** [comment]
@Wumpf here is the discussion that prompted this: https://matrix.to/#/!FZyQrssSlHEZqrYcOb:matrix.org/$p_e4sAf-9ghc9fGryzvdu1mQnPXmMCkyerIW7D3jrbM?via=matrix.org&via=mozilla.org&via=fairydust.space

**Review by cwfitzgerald — APPROVED** [review]
Looks good, can we get a bit of documentation about what the feature is?

**Comment by crowlKats** [comment]
@cwfitzgerald sure; done. We need a metal-rs release first before landing though; is this something you could do?

**Pull request merged**
