### PR TITLE
Rendy integration

### LINKED ISSUE #111: Generic descriptor set allocator
We currently just have a global descriptor pool, which is very limited - see #110
Relevant code - https://github.com/gfx-rs/wgpu/blob/61e7692e3693d9e60e8eab78c79fc5e3e913237d/wgpu-native/src/device.rs#L385

### PR DESCRIPTION
**Pull request by kvark**
Integrates with rendy-memory and rendy-descriptor.
~~Includes #195~~
Fixes #111

### CODE REVIEW

**Comment by rukai** [comment]
I'm getting this panic on my project (the same code that was triggering https://github.com/gfx-rs/wgpu/issues/181):

```
thread 'main' panicked at 'key not present', src/libcore/option.rs:1036:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1036
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: wgpu_native::device::Device<gfx_backend_vulkan::Backend>::maintain
  12: wgpu_queue_submit
  13: brawllib_rs::renderer::render_gif
  14: rukaidata_website::gif::generate
  15: rukaidata_website::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  19: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
Illegal instruction (core dumped)
```

**Comment by rukai** [comment]
Repro here: https://github.com/rukai/wgpu-rs/blob/rendy_descriptor_bug/examples/repro/main.rs
Its very similar to the repro in https://github.com/gfx-rs/wgpu/issues/181

I just replaced `state.device.get_queue().submit(&[]);` with `device.poll()` and added `command_encoder.copy_texture_to_buffer(framebuffer_copy_view, framebuffer_out_copy_view, texture_extent);`

**Comment by kvark** [comment]
@rukai thank you for another great test case! I don't think it's particularly related to the PR, but the fix is also included now both in this and the base PRs.

**Comment by rukai** [comment]
Yep that fixes it! ... I think that fixes all my problems for real this time.

**Comment by kvark** [comment]
@omni-viral something is weird about STORAGE descriptors. I'm getting the following error in an app:
> ERROR 2019-05-30T03:12:06Z: gfx_backend_vulkan: 
VALIDATION [VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307 (0)] : Unable to allocate 1 descriptors of type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE from pool 0x2. This pool only has 0 descriptors of this type remaining. The Vulkan spec states: descriptorPool must have enough free descriptor capacity remaining to allocate the descriptor sets of the specified layouts (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307)
object info: (type: DESCRIPTOR_POOL, hndl: 2)

Given that the descriptor pool is now managed by rendy-descriptor, it would happen when I either incorrectly provide the descriptor set layout bindings, or there is bug in rendy-descriptor.

**Comment by kvark** [comment]
Thank you!
Bors r=grovesNL

**Pull request merged**
