### PR TITLE
Implement debug marker support

### PR DESCRIPTION
**Pull request by krupitskas**
**Connections**
Closes https://github.com/gfx-rs/wgpu/issues/697

**Description**
Looks like because I've once pushed forward reset branch to my master, previous pull request https://github.com/gfx-rs/wgpu/pull/713
show that there no commits and it automatically was closed :/

**Testing**
Not tested yet

### CODE REVIEW

**Comment by krupitskas** [comment]
@kvark Trying to compile wgpu-rs with wgpu as backend, have an issues:
```
error[E0560]: struct `wgpu_core::binding_model::BufferBinding` has no field named `buffer`
   --> src\backend\direct.rs:417:29
    |
417 | ...                   buffer: buffer_slice.buffer.id,
    |                       ^^^^^^ `wgpu_core::binding_model::BufferBinding` does not have this field
    |
    = note: available fields are: `buffer_id`, `offset`, `size`


```
Is it parted a bit?

**Comment by kvark** [comment]
@krupitskas there should be no need to create a new PR. You can just force-push the changes to the old branch to update the PR.

Also, please rustfmt stable on the code.

> Is it parted a bit?

As always, there is an update in progress - https://github.com/gfx-rs/wgpu-rs/pull/370
You can base on top of it. I'm merging it soon.

**Comment by krupitskas** [comment]
I'm tried cargo fmt in wgpu folder, in wgpu-core and even in clion, no changes  ¯\_(ツ)_/¯

**Comment by kvark** [comment]
Can you post your `rustfmt --version`? We use one coming from `runstup component add rustfmt`.

**Comment by krupitskas** [comment]
```
rustfmt --version
rustfmt 1.4.14-stable (e4173566 2020-04-21)
```

Also, while I started writiing an example, I've realized that `trait RenderInner<Ctx: Context>` haven't any function to call unsafe `insert_debug_marker`.
Should I add it here?

**Comment by krupitskas** [comment]
изображение
Inserted debug marker in wgpu-rs "cube" example. I will copy paste it and also create an example called "debug_markers"

**Comment by krupitskas** [comment]
With color "1" it becomes black, whoa! (Never saw it, always used default colors in previous projects)
Cool feature though

изображение

**Comment by krupitskas** [comment]
Here is an example.
https://github.com/gfx-rs/wgpu-rs/pull/374
I've followed [API](https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-pushdebuggroup) and didn't include color set up, but may be we can?

**Comment by kvark** [comment]
> Also, while I started writiing an example, I've realized that CommandEncoder haven't any function to call unsafe insert_debug_marker.
Should I add it here?

Indeed, this should be available in `CommandEncoder` as well.

**Comment by kvark** [comment]
> Also another question. I've provided color parameter, but webgpu wiki doesn't say anything about color, it's alright?)

That's fine, we'll just ignore the color when targeting the web :)

**Comment by krupitskas** [comment]
I'm a bit lost track. Here in wgpu, we have support for debug markers. In wgpu-rs I've added support into `CommandEncoder`, but I can't see in wgpu a place where should I also add an "abstraction layer".
I've looked for stuff like `wgpu_render_pass_draw_indexed`  in `wgpu` but found only exactly this declaration.
So looks like pull request, which I've submitted for `wgpu-rs` with `CommandEncoder` additions is correct one and this pull request can be merged?

**Comment by kvark** [comment]
@krupitskas in `wgpu` we'd have these methods on command encoder [near here](https://github.com/gfx-rs/wgpu/blob/d1deae5747f5bd0a6503c1462555f201eaae02c9/wgpu-core/src/command/mod.rs#L255).
You'd add something like
```rust
```

**Comment by kvark** [comment]
Thank you!
bors r+

**Pull request merged**
