### PR TITLE
Check render bundle encoding for RODS

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Matches https://github.com/gpuweb/gpuweb/pull/1979

**Description**
Allows render bundles to be encoded for RODS.
In addition, validates that bundle RODS matches the pass RODS when executing. This part of the spec isn't written yet, and it's safer to be on the strict side.

**Testing**
Untested

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
bors r+

**Comment by cwfitzgerald** [comment]
Errr
bors r-

r=me when CI isn't mad :)

**Comment by kvark** [comment]
bors r=cwfitzgerald

**Comment by kvark** [comment]
bors r=cwfitzgerald

**Comment by kvark** [comment]
bors r=cwfitzgerald

**Pull request merged**
