### PR TITLE
Implement resolve query set (#3489

### PR DESCRIPTION
**Pull request by JolifantoBambla**
**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Description**
_Describe what problem this is solving, and how it's solved._
I've added the missing `BufferUsages::QUERY_RESOLVE` (https://www.w3.org/TR/webgpu/#buffer-usage) and implemented `command_encoder_resolve_query_set` for the WebGPU backend.

**Testing**
Unfortunately, the [WebGPU backend is broken in v0.15.1](https://github.com/gfx-rs/wgpu/issues/3430), so I only tested this with a personal project and [my own patch for v0.14.2](https://github.com/JolifantoBambla/wgpu/tree/implement-timestamp-query-on-v0.14.2).

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
This is a good start, but I can merge this just yet - because this brings us in line with the upstream api, we also need the native api to behave the same. Once this merges, you'd need two different sets of flags to do query resolves.

This should also change the validation of the resolve query to check for the RESOLVE_QUERY usage. If anything is confusing about that transformation, please feel free to ask questions over on the matrix.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
As this is a breaking change, could you add an entry in the "major changes" explaining what changed? After that, this looks g2g

**Comment by JolifantoBambla** [comment]
done :)
I also fixed the mipmap example - missed that one before
I don't know why the shader test (`shader::zero_init_workgroup_mem::zero_init_workgroup_mem`) fails though

**Review by cwfitzgerald — APPROVED** [review]
Thanks!

**Pull request merged**
