### PR TITLE
Replace gfx-memory by gpu-alloc

### LINKED ISSUE #1011: Move from gfx-memory to gpu-alloc
**Is your feature request related to a problem? Please describe.**
gfx-memory was inherited from rendy-memory and heavily patched and refactored. It still has issues, and it requires more drastic changes than refactoring. https://github.com/zakarumych/gpu-alloc is a new crate (by the same author) that will likely be used more widely in Rust community, not directly limited by gfx-rs ecosystem. It's general allocator is also much simpler, and I hope that it works better :)

**Describe the solution you'd like**
Replace gfx-memory dependency by https://github.com/zakarumych/gpu-alloc
First, we'll depend on github revision and report issues. Then they will release by the time we need it for wgpu-0.7

**Describe alternatives you've considered**
Keep working on gfx-memory. Honestly, not super excited about that :)

**Additional context**

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Fixes #1011
Blocked on:
- https://github.com/zakarumych/gpu-alloc/issues/4
- https://github.com/zakarumych/gpu-alloc/pull/14
- https://github.com/zakarumych/gpu-alloc/issues/16

**Description**
Moves us to gpu-allocator, which should be simpler and better supported than gfx-memory.

**Testing**
Untested and unfinished (to be updated)

### CODE REVIEW

**Comment by kvark** [comment]
@zakarumych could you double-check the configuration values here, for sanity?

**Review by cwfitzgerald — APPROVED** [review]
Nothing looks out of place to me. Excited to see how this helps gfx development :)

**Comment by kvark** [comment]
bors r=cwfitzgerald

**Comment by zakarumych** [comment]
You just copied them from `Config::i_am_prototyping`, right?
Looks alright for modern GPU.
`GpuAllocator` also bounds sizes and tresholds by fractions of heap size, so it won't pre-allocate chunks too close to whole heap size, so event with `!0 / 2 + 1` for those parameters it should work fine.

**Pull request merged**
