### PR TITLE
Ensure we pick the right gpu card in the example backend

### LINKED ISSUE #6522: Pick supported adapter for examples
**Description**
On laptops with multiple graphics cards, when trying to run the raytracing examples I get the panic:
```
[2024-11-12T03:05:39Z WARN  winit::platform_impl::platform::x11::xdisplay] error setting XSETTINGS; Xft options won't reload automatically
[2024-11-12T03:05:39Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1.6666666666666667
[2024-11-12T03:05:39Z INFO  wgpu_examples::framework] Initializing wgpu...
[2024-11-12T03:05:40Z INFO  wgpu_core::instance] Adapter AdapterInfo { name: "AMD Radeon Graphics (RADV RENOIR)", vendor: 4098, device: 5688, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 24.0.9-0ubuntu0.1", backend: Vulkan }
[2024-11-12T03:05:40Z INFO  wgpu_examples::framework] Using AMD Radeon Graphics (RADV RENOIR) (Vulkan)
thread 'main' panicked at examples/src/framework.rs:291:9:
Adapter does not support required features for this example: Features(EXPERIMENTAL_RAY_TRACING_ACCELERATION_STRUCTURE | EXPERIMENTAL_RAY_QUERY)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
 
**Repro steps**
Run the raytracing example on a laptop with an AMD integrated graphics card and a NVidia RTX card.
```
 cargo run --bin wgpu-examples ray_cube_compute
```

**Expected vs observed behavior**
Ideally, we should be able to select the right graphics card prior to instantiating a raytracing pipeline. I'd be open to helping push this along but have limited knowledge of `wgpu`.

**Platform**
Ubuntu 24.04 on a Razer Blade 14 AMD Ryzen 9 5900HX with RTX3060.

### PR DESCRIPTION
**Pull request by arjo129**
**Connections**
fixes #6522 

**Description**
This is my first time contributing to this project, so it may be that I'm doing something wrong. Essentially, we retain the old behavior if we use the environment variable to select our gpu. Otherwise we first try to match required features prior to selecting an adapter.

**Testing**

Just run the example as done before.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
thanks for your contribution! looks good to me!

**Comment by Wumpf** [comment]
ah but I think this will fail wasm ci because `enumerate_adapters` is native only, let's see

**Review by Wumpf — CHANGES_REQUESTED** [review]
yeah, this still needs special handling for wasm (and fix unused warnings) - that checklist on the PR template is there for a reason ;-)

**Comment by arjo129** [comment]
Thanks @Wumpf for pointing that out. Sorry about that. I've fixed wasm support by refactoring this logic out into a seperate function.

**Review by Wumpf — APPROVED** [review]
no worries!
a little bit much c&p for my taste, but this will do just fine :)

**Comment by Wumpf** [comment]
apologies for the long delay to merge! Somehow lost track of this

**Pull request merged**
