### PR TITLE
[0.5] Various correctness fixes

### PR DESCRIPTION
**Pull request by kvark**
Includes the pipeline layout fix, read-only usage fix, and the improved error messages.
Everything is backwards-compatible.

### CODE REVIEW

**Comment by aloucks** [comment]
@kvark Was there some reason why the max vertex buffer fix was excluded? https://github.com/gfx-rs/wgpu/pull/562

I assumed it would be rolled into the next release but I'm still seeing the issue and when I check the source under `~/.cargo/registry` the code changes are missing.

**Comment by kvark** [comment]
@aloucks I didn't realize you'd be needing this patch, my apologies!
I also have doubts around the value of 16 exposed there. After I filed https://github.com/gpuweb/gpuweb/issues/693, we discussed it a bit with the group. It looks like for the near future we can at most guarantee 14 vertex buffers, but that requires us to expose only 4 bind groups on Metal. My (rather strong) preference is to instead:
  - expose 8 vertex buffers
  - expose 8 bind groups
  - reconsider this once we are closer to implementing Metal argument buffers

So I think your PR may need to be rolled back, unfortunately. The base limit will need to stay as 8. And we'll want to use `ArrayVec` instead of `SmallVec` for the storage anyway, to avoid touching the heap.

On your side, some process is needed to interleave vertex data coming from glTF before it reaches us.

**Comment by aloucks** [comment]
@kvark It's confusing that this repository doesn't actually represent the source code that's published to crates.io. It seems like things are being cherry-picked into some other repo and then published from there. I know that there is some sync setup with a mozilla repository but I assumed that it was a 1:1 mirror of this one. Is that not the case?

What repository represents the system of record for these crates? Do they have tags?

**Comment by kvark** [comment]
@aloucks 
This repository *does* represent the published code. Latest https://crates.io/crates/wgpu/0.5.0 was published from the corresponding [v0.5](https://github.com/gfx-rs/wgpu/tree/v0.5) branch here, and this is where backported fixes go, like this very PR.

This has nothing to do with mozilla repositories, it's the workflow we use everywhere: gfx-rs, ron, you name it. I've yet to see an alternative that works, so I dunno what you expect.

**Comment by aloucks** [comment]
@kvark 

> Latest https://crates.io/crates/wgpu/0.5.0 was published from the corresponding v0.5 branch here

Ah, Ok! I had not seen that branch. I was looking at master and saw that the changes weren't reflected in the crates.io code. Thanks for clearing that up.

**Pull request merged**
