### PR TITLE
Fix error with resolver=1 on non-Windows

### PR DESCRIPTION
**Pull request by kvark**
**Connections**

**Description**
Many users stumble upon this.

**Testing**
Manually tested

### CODE REVIEW

**Comment by kvark** [comment]
The new error:
```
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /Users/dmalyshau/Code/wgpu/wgpu-hal/src/lib.rs:47:1
   |
47 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `super::dx12`
  --> /Users/dmalyshau/Code/wgpu/wgpu-hal/src/lib.rs:62:20
   |
62 |     pub use super::dx12::Api as Dx12;
   |                    ^^^^ could not find `dx12` in the crate root

error: aborting due to 2 previous errors

```

**Comment by cwfitzgerald** [comment]
This pr is fine, but it won't actually be hit, d3d12-rs fails to compile first

**Comment by kvark** [comment]
> This pr is fine, but it won't actually be hit, d3d12-rs fails to compile first

the subject of the issue was wrong. It's fixing resolver=1 on *non* windows.
d3d12-rs isn't compiled now because the PR moves it to windows-only dependencies

**Pull request merged**
