### PR TITLE
Pull out code motion from arcanization

### PR DESCRIPTION
**Pull request by jimblandy**
The arcanization PR #3626 includes a bunch of code motion, in particular breaking `wgpu-core/src/hub.rs` into several different modules. This introduces a lot of noise around imports and paths, and makes it hard to see what has been done to the contents of those modules.

This PR splits out the code motion. It's easy to 'merge' this into the real arcanization branch simply by:
1) merging `trunk` into `gents83/master` as has been done several times before
2) rebasing this PR onto the same `trunk` commit that was just merged into `gents83/master` and committing that as the new `trunk`
3) 'merging' that `trunk` into `gents83/master` in a way that accepts no changes from `trunk`

The resulting diff against trunk is substantially easier to review.

This PR is marked as a draft at the moment, since I'd still like to do `registry.rs` and `storage.rs`, and maybe the two new modules in `device`.

### CODE REVIEW

**Comment by gents83** [comment]
Thanks for this! It's a very smart way to handle that big CL

**Comment by jimblandy** [comment]
I believe all the commits in this PR are individually CI-safe, so we probably don't need to squash.

**Comment by jimblandy** [comment]
and I think they're all just code motion, path adjustments and `use` tweaks.

**Review by teoxoy — APPROVED** [review]
It's unfortunate that git can't detect that part of the code from `device/mod.rs` was moved to `device/global.rs` and blame won't work past the commit in this PR but I don't see a solution for it and that file was getting increasingly large.

Otherwise looks good!

**Pull request merged**
