### PR TITLE
style: simplify string hashes for readability

### PR DESCRIPTION
**Pull request by hamirmahal**
**Description**
There are some unnecessary raw string hashes.

This pull request removes them to improve readability and maintainability.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
- [x] Run `cargo xtask test` to run tests.

I ran this locally, but it errored.

```
$  cargo xtask test
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `xtask/target/debug/xtask test`
[INFO  xtask::test] Generating .gpuconfig file based on gpus on the system
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/wgpu-info --json -o .gpuconfig`
[INFO  xtask::test] Found 3 gpus
[INFO  xtask::test] Running cargo tests
error: no such command: `nextest`

	Did you mean `test`?

	View all installed commands with `cargo --list`
	Find a package to install `nextest` with `cargo search cargo-nextest`
Error: Tests failed

Caused by:
    command exited with non-zero code `cargo nextest run --benches --tests --no-fail-fast --all-features --retries 0`: 101
```

- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

I didn't update `CHANGELOG.md` for this because it's not user-facing.

**Comment by FrankenApps** [comment]
Personally I see no reason why the hashtags should be removed. I think its perfectly readable with them.

**Comment by Wumpf** [comment]
thanks for wanting to contribute to the project!
However, we generally don't take PRs that are of purely cosmetic nature unless they address some widely agreed style issue. Not quite seeing that here, so closing this. Please re-open if you have some additional stronger arguments why this should go in.

Regarding test execution: you have to install `nextest`, see https://github.com/gfx-rs/wgpu?tab=readme-ov-file#core-test-infrastructure

**Comment by hamirmahal** [comment]
You're welcome!

The only argument I have for this change is to reduce clutter and therefore improve code readability and maintainability.

**Pull request closed without merging**
