### PR TITLE
Sync changes from mozilla-central gfx/wgpu

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by moz-gfx** [comment]
bors r=auto

**Comment by aloucks** [comment]
These sync PRs seem very odd. It seems like the changes they're trying to apply already exist in many cases. The source branch is also quite far behind. Shouldn't it be rebased before attempting to push back upstream?

**Comment by kvark** [comment]
@staktrace so this time I removed `github-sync` branch from `moz-gfx` account fork. Apparently, it doesn't solve the problem.

**Comment by kvark** [comment]
@aloucks yeah, I very much want the code to be rebased before making the PR. We just need to set it up this way in Gecko scripts :/

**Pull request closed without merging**
