### PR TITLE
Update C example

### PR DESCRIPTION
**Pull request by grovesNL**
- Move `winit` behind a feature in wgpu-native
- Update C example to newer wgpu-native API
- Expose `Id` as `repr(C)`
- Add clang-format configuration for C files
- Add C example to CI (we can move parts of this back into the Makefile in a follow-up PR)

### CODE REVIEW

**Comment by grovesNL** [comment]
@floooh how does b2c58c7 look to you (for nested designated initialization)? I tried using the default clang-format style in VSCode, but I'm not sure whether this spacing is typical for C projects.

**Comment by floooh** [comment]
in some cases it looks a bit strange, e.g.

```c
  WGPUBindGroupLayoutId bind_group_layout =
      wgpu_device_create_bind_group_layout(device,
                                           &(WGPUBindGroupLayoutDescriptor){
                                               .bindings = NULL,
                                               .bindings_length = 0,
                                           });
```
I would move the somewhat extreme indentations to the front:

```c
WGPUBindGroupLayoutId bind_group_layout =
    wgpu_device_create_bind_group_layout(device,
        &(WGPUBindGroupLayoutDescriptor){
            .bindings = NULL,
            .bindings_length = 0,
        });
```
But if indentation tools like clang-format disagree, then maybe it's better to go with the clang style :)

**Comment by floooh** [comment]
PS: also C99 designated init zero-initializes missing members. In sokol_gfx.h I took care that "zero-initialized" means "default". I'm not sure if that's also the case in the WGPU C-API, if yes a few of the "= 0" or "= NULL" items could probably be removed (but one minor problem I encountered: when all items should be default, one must say "= { 0 };", not "= { };", and GCC has a 'false' warning for the "= { 0 };" about missing initializer items.

**Comment by grovesNL** [comment]
Thanks for taking a look! I agree about the left indentation, it appears there are a couple flags to set this in clang-format that makes this look more reasonable IMO:
```
IndentWidth: 4
AlignOperands: false
AlignAfterOpenBracket: DontAlign
```

I'll take a look at the defaults too – I think zero initializing to `{ 0 }` might already work for some of these descriptors. I don't think it's been a goal of WebGPU so far, but even the JavaScript API might benefit from assuming zero for incomplete descriptors.

**Comment by grovesNL** [comment]
@kvark I think this should be ready now if you want to take a look. I added the C example back into CI to catch API changes for now (we can move parts of this back into the Makefile afterwards).

**Pull request merged**
