### PR TITLE
Compute max workgroup size limits

### PR DESCRIPTION
**Pull request by UpsettingBoy**
**Connections**
#1808

**Description**
Added Limits for compute operations (workgroup sizes) and a check during a _normal_ dispatch operation.

I cannot currently add these new Limits to Metal and GLES because no autocompletion under Windows for them (OpenGL drivers should be installed but there is not even a compatible device ¯\_(ツ)_/¯ ).

Also, I think, since now we have max_workgroup_size_(x,y,z) a validation on compute shaders about their workgroup_size should be possible.

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
Nice work!

**Comment by kvark** [comment]
I pushed GLES implementation into your branch, please pick it up locally for further changes.

**Comment by UpsettingBoy** [comment]
Thanks!! I pick your commit locally. Only Metal reamining then.

Also, I have a question . As I understood the WebGPU specification, the [dispatch ](https://gpuweb.github.io/gpuweb/#dom-gpucomputepassencoder-dispatch)operation can only be executed if its dimensions are <= than [maxComputeWorkgroupsPerDimension ](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxcomputeworkgroupsperdimension); but when testing, I can execute a dispatch with values greater than the limit without any problem. Am I missing something?

**Comment by kvark** [comment]
Also pushed Metal now. Wasn't able to find the relevant limit in the tables, so just put defaults.

**Comment by kvark** [comment]
@UpsettingBoy what are you testing exactly?
Your PR is adding this validation, so obviously nothing will error on wgpu side until your PR is merged.

**Comment by UpsettingBoy** [comment]
I was testing if a program would crash if the dispatch dims are greater than the limits reported, but it didn't.

**Comment by kvark** [comment]
Doing this is invalid usage. This is literally off-limits territory, it's undefined behavior - anything can happen, including not crashing.

**Comment by UpsettingBoy** [comment]
Alright, thanks for the clarification!! I think this PR is ready then.

**Review by kvark — APPROVED** [review]

**Pull request merged**
